### ISSUE TITLE
a fun todo list

### ISSUE THREAD

**Issue by kehrazy** [es3n1n/portal2-internal#12]
https://github.com/es3n1n/portal2-internal/blob/823110d3ee743a8561cbb4f1b2e427ae1cbe4731/portal2-internal/sdk/misc/color_t.hpp#L49-L61

This should be a truth table, with the values assigned at the top. A temporary color_t construction would be clearer, imo:
```cpp
[[nodiscard]] color_t from_hsb(float h, float s, float b) {
   color_t tmp{};
   //
   //
   //: do stuff..
   
   switch(h):
      case 1:
         tmp.r = ...;
         tmp.b = ...;
         tmp.g = ...;
         return tmp;
      case 2:
         tmp.r = ...;
         tmp.b = ...;
         tmp.g = ...;
         return tmp;
```
et cetera.

- [x] done / fixed / invalid

---

https://github.com/es3n1n/portal2-internal/blob/823110d3ee743a8561cbb4f1b2e427ae1cbe4731/portal2-internal/sdk/misc/color_t.hpp#L6-L6

Those should be uint8_t. So should be the parameters in member functions.

- [x] done / fixed / invalid

---

https://github.com/es3n1n/portal2-internal/blob/823110d3ee743a8561cbb4f1b2e427ae1cbe4731/portal2-internal/sdk/misc/color_t.hpp#L19-L21

This is highly unsafe. This probably should just error out on shit data.

- [x] done / fixed / invalid

---

https://github.com/es3n1n/portal2-internal/blob/823110d3ee743a8561cbb4f1b2e427ae1cbe4731/portal2-internal/sdk/misc/color_t.hpp#L25-L25

I suggest this:
```cpp
    std::uint32_t get_hex() {
        auto get_hex_byte = [&](std::uint8_t field, unsigned shift_amt) -> std::uint8_t {
            return (field & 0xff) << shift_amt;
        };
        
        enum {
            ALPHA = 24,
            RED = 16,
            GREEN = 8,
            BLUE = 0
        };

        return  get_hex_byte(this->a, ALPHA) |
                get_hex_byte(this->r, RED) |
                get_hex_byte(this->g, GREEN) |
                get_hex_byte(this->b, BLUE);
    }
```

- [x] done / fixed / invalid

---

Throughout the project you use `#pragma once` directives.

These were not supported by GCC. (Yeah, it was a long time ago. Poor little GNU compiler). Still, the `#ifndef MY_SHIT` is highly preferrable.

- [x] done / fixed / invalid

---

https://github.com/es3n1n/portal2-internal/blob/823110d3ee743a8561cbb4f1b2e427ae1cbe4731/portal2-internal/sdk/misc/client_class.hpp#L6-L7

- Why not `using create_client_class_fn`? more modern shit, looks cool, LSP's love them.

- Should these be publicly available?

- [x] done / fixed / invalid

---

https://github.com/es3n1n/portal2-internal/blob/823110d3ee743a8561cbb4f1b2e427ae1cbe4731/portal2-internal/sdk/misc/vec_t.hpp#L11

Clang optimizes these away. This just restricts the usage availability.

- [x] done / fixed / invalid

---

There's probably a lot more that needs to be done, but these are the only ones that i've found.

**Comment by es3n1n** [comment]
Thank you so much. Yeah this project is a legacy mess. I'll see what could be done (hopefully) tmr.

**Comment by es3n1n** [comment]
finally got some free time to look at this, just pushed initial changes that you can review here #14

**Comment by es3n1n** [comment]
as for the color_t::blend function, i think with proper types channel_t/flt_range_t there shouldn't be that many ub cases

**Comment by es3n1n** [comment]
i think we'll still stick to `#pragma once` for now, since i highly doubt that in the current state this project can even be compiled using gcc or clang, but i never really tested though

**Comment by es3n1n** [comment]
i think we are done here
